
#spring config properties
spring.config.import=optional:file:.env[.properties]


spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# JWT
jwt.secret=MzY2YjM1YjRmNjg2YjY1ZjUyNjU0ZGI0YjY1YzQ2YzQ2YzQ2YzQ2YzQ2YzQ2YzQ2YzQ2Yw==
jwt.expiration=86400000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false